"use client";

import { useState } from "react";
import { format, startOfWeek } from "date-fns";
import { CalendarRange, LoaderCircle, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";

type Session = { assignmentId: string; title: string; durationMinutes: number; rationale: string };
type Day = { date: string; focus: string; sessions: Session[] };
type Plan = { id: string; title: string; start_date: string; end_date: string; plan: { summary?: string; days?: Day[] } };

export function StudyPlanner({ initialPlans, openAssignmentCount }: { initialPlans: Plan[]; openAssignmentCount: number }) {
  const [plans, setPlans] = useState(initialPlans); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [active, setActive] = useState<Plan | null>(initialPlans[0] ?? null);
  async function generate() { setPending(true); setError(null); const weekStart = startOfWeek(new Date(), { weekStartsOn: 1 }); const response = await fetch("/api/study-plans", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startDate: format(weekStart, "yyyy-MM-dd") }) }); const body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error ?? "Could not create a study plan."); else { const plan = body.plan as Plan; setPlans((items) => [plan, ...items]); setActive(plan); } setPending(false); }
  return <div className="grid gap-6 xl:grid-cols-[280px_minmax(0,1fr)]"><aside className="card h-fit p-4"><Button className="w-full" disabled={!openAssignmentCount || pending} onClick={generate}>{pending ? <><LoaderCircle className="animate-spin" size={16} />Planning…</> : <><Sparkles size={16} />Plan this week</>}</Button><p className="mt-3 text-xs leading-5 text-slate-500">StudyOS schedules only the open assignments in your workspace. It will not invent work that does not exist.</p>{error && <p role="alert" className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<p className="mt-5 px-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Saved plans</p><div className="mt-2 space-y-1">{plans.map((plan) => <button key={plan.id} onClick={() => setActive(plan)} className={`w-full rounded-lg px-2.5 py-2 text-left text-sm ${plan.id === active?.id ? "bg-emerald-50 font-medium text-emerald-800" : "text-slate-600 hover:bg-slate-50"}`}><span className="block truncate">{plan.title}</span><span className="mt-0.5 block text-xs font-normal text-slate-400">{plan.start_date}</span></button>)}</div></aside><section>{active ? <div className="space-y-5"><div className="card p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><CalendarRange size={20} /></span><div><h2 className="font-semibold">{active.title}</h2><p className="mt-1 text-sm text-slate-500">{active.start_date} — {active.end_date}</p></div></div>{active.plan.summary && <p className="mt-4 border-t border-slate-100 pt-4 text-sm leading-6 text-slate-600">{active.plan.summary}</p>}</div><div className="grid gap-4 md:grid-cols-2">{active.plan.days?.map((day) => <article key={day.date} className="card p-5"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">{format(new Date(`${day.date}T12:00:00`), "EEEE · MMM d")}</p><h3 className="mt-1 font-semibold">{day.focus}</h3><div className="mt-4 space-y-3">{day.sessions.map((session, index) => <div key={`${session.assignmentId}-${index}`} className="rounded-xl bg-slate-50 p-3"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-slate-800">{session.title}</p><span className="shrink-0 text-xs font-semibold text-emerald-700">{session.durationMinutes} min</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{session.rationale}</p></div>)}</div></article>)}</div></div> : <EmptyState title={openAssignmentCount ? "Turn your work into a week" : "Add open assignments first"} copy={openAssignmentCount ? "Generate a schedule that balances deadlines, priority, and estimated work — using only your actual assignments." : "The planner needs assignment deadlines and workload estimates before it can build a useful schedule."} />}</section></div>;
}
