"use client";

import { useState } from "react";
import { FileUp, LoaderCircle, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/status-badge";
import { supportedDocumentAccept } from "@/lib/documents/formats";
import type { Course, StudyDocument } from "@/types/domain";

export function DocumentManager({ initialDocuments, courses, selectedCourseId }: { initialDocuments: StudyDocument[]; courses: Course[]; selectedCourseId?: string }) {
  const [documents, setDocuments] = useState(initialDocuments); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  async function upload(formData: FormData) { setPending(true); setError(null); setNotice(null); const response = await fetch("/api/documents", { method: "POST", body: formData }); const body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error ?? "Upload failed."); else { if (body.document?.id) setDocuments((items) => [body.document as StudyDocument, ...items.filter((item) => item.id !== body.document.id)]); setNotice(body.warning ?? "Your document is ready for grounded questions and flashcards."); } setPending(false); }
  async function remove(document: StudyDocument) { if (!window.confirm(`Delete ${document.original_filename}? Its extracted chunks and embeddings will be removed too.`)) return; const response = await fetch(`/api/documents/${document.id}`, { method: "DELETE" }); if (response.ok) setDocuments((items) => items.filter((item) => item.id !== document.id)); else setError("Unable to delete this document."); }
  return <div className="space-y-6"><form action={upload} className="card grid gap-4 p-5 lg:grid-cols-[1fr_240px_auto]"><label><span className="label">Study file</span><input className="field file:mr-3 file:rounded-lg file:border-0 file:bg-emerald-50 file:px-2 file:py-1 file:text-sm file:font-medium file:text-emerald-800" name="file" type="file" accept={supportedDocumentAccept} required /></label><label><span className="label">Associate with course</span><select className="field" name="courseId" defaultValue={selectedCourseId ?? ""}><option value="">No course selected</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.course_code ? `${course.course_code} — ` : ""}{course.name}</option>)}</select></label><div className="flex items-end"><Button className="w-full" type="submit" disabled={pending}>{pending ? <><LoaderCircle className="animate-spin" size={16} />Processing…</> : <><FileUp size={16} />Upload file</>}</Button></div><p className="text-xs leading-5 text-slate-500 lg:col-span-3">PDF, Word (.docx), PowerPoint (.pptx), Excel (.xlsx/.xls), CSV, text, or Markdown · 15 MB maximum · files stay private to your account.</p></form>{error && <p role="alert" className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}{notice && <p role="status" className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{notice}</p>}{documents.length ? <div className="card overflow-hidden"><div className="hidden grid-cols-[minmax(0,1.5fr)_1fr_.7fr_auto] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500 md:grid"><span>Document</span><span>Course</span><span>Status</span><span /></div>{documents.map((document) => <div key={document.id} className="grid gap-3 border-b border-slate-100 px-5 py-4 last:border-0 md:grid-cols-[minmax(0,1.5fr)_1fr_.7fr_auto] md:items-center md:gap-4"><div><p className="truncate text-sm font-medium text-slate-800">{document.original_filename}</p><p className="mt-1 text-xs text-slate-500">{Math.max(1, Math.round(document.file_size / 1024))} KB · Uploaded {new Date(document.created_at).toLocaleDateString()}</p>{document.processing_error && <p className="mt-1 text-xs text-rose-600">{document.processing_error}</p>}</div><span className="text-sm text-slate-600">{document.courses?.course_code ?? document.courses?.name ?? "Unassigned"}</span><span><StatusBadge value={document.processing_status} /></span><button onClick={() => remove(document)} aria-label={`Delete ${document.original_filename}`} className="justify-self-end rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-700"><Trash2 size={17} /></button></div>)}</div> : <EmptyState title="Bring your material into StudyOS" copy="Upload notes, readings, slides, spreadsheets, syllabi, or study guides. They will become available to the grounded AI assistant." />}</div>;
}
